---
title: "ENVS 193DS Final"
date: "6/4/26" 
author: "Steven Le"
format: 
  pdf:
    toc: true 
execute:
  warning: false
  message: false
editor: source
include-in-header:
      text: |
        \usepackage{fvextra}
        \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,commandchars=\\\{\}}
---

# Homework set up

[GitHub repo link](https://github.com/lesteven24/ENVS-193DS_spring-2026_final.git)

```{r}

#read in packages
library(tidyverse)
library(here)
library(janitor)
library(readxl)
library(ggplot2)
library(ggeffects)
library(flextable)
library(here)
#stored nest data as an object called nest
nest <- read_csv(here("data", "nest_data_final.csv"))

```

# Problem 1. Research writing 

## a.

In part 1, they used a logistic regression, which is a generalized linear model with a binomial error distribution.  In part 2, they used a chi-square test, which is used to identify if there is a relationship between two categorical variables.  

## b.

### Part 1.

The distance to water edge does seem to predict the probability of American Avocet microhabitat use.  

### Part 2. 

There does seem to be a relationship between bird species (American Avocet, Forster’s Tern, Black-necked Stilt) and habitat (managed pond, non-tidal marsh, salt pond, tidal marsh, or tidal mudflat).  

## c.

One additional variable that could influence the probability of American Avocet microhabitat use is the type of behavior they were displaying, which is a categorical variable.  For the American Avocets, the researchers put behavior into four main categories: feeding (searching, probing, and dunking bills into the water), roosting (standing, sitting, preening), breeding (nest-building, incubating, brooding chicks, alarm calling, breeding display, copulation, or predator distraction display), and other (walking, swimming, or flushing).  This variable might influence American Avocet habitat use as different behaviors can change the duration of how long they remain in a particular habitat.    

# Problem 2. Data analysis 

## a.



## b.



## c.



## d.



## e.



## f.



## g.



## h.



## i.



## j.



## k.



# Problem 3. Affective and exploratory visualizations 

## a.



## b.



## c.



## d.



## e.



## f.



## g.

